### ISSUE TITLE
When BASE_PATH is not absolute path, builder crashes, because WebSocket URL is not properly created

### ISSUE THREAD

**Issue by PremyslCerny** [TeskaLabs/asab-webui#110]
Config:

```
	app: {
		BASE_URL: '/',
		...
```

The constructed WebSocket URL is

```
/api/lmio_parser_builder/...
```

But it should be:

```
ws://hostname/api/lmio_parser_builder/...
```

see my hotfix: https://github.com/TeskaLabs/asab-webui/commit/90f68f5100beea5c4a3358651f0c68ee284d8d9a

**Comment by ateska** [comment]
OK,  I see.

The correct fix is that `this.getServiceURL()` should always return the absolute URL, starting with `http://` ... this is obviously not the case here and it should be fixed then. @Pe5h4 
 
`BASE_URL` should not be set to `/` ... also, I strongly recommend to NOT USE `BASE_URL` in configurations.
ASAB WebUI is (should be) clever enough to detect proper BASE_URL from the browser.

**Comment by ateska** [comment]
The hot fix needs to be eventually removed, it is a bit misleading.

**Comment by ateska** [comment]
Once discussion here is over, we need to update this: http://wiki.teskalabs.int/rd/projects/asab-webui/configuration/url-config#base_url ... specifying that `BASE_URL` has to be absolute (if that will be the case).
