### ISSUE TITLE
DataTable in demo should not use the app configuration

### ISSUE THREAD

**Issue by ateska** [TeskaLabs/asab-webui#112]
https://github.com/TeskaLabs/asab-webui/blob/f27fd882f1aa0e267de9b5c450c9225099fb9496/demo/src/modules/home/containers/TableContainer.js#L134

Because the information/configuration is not co-located and difficult to locate.

The config (headers and limit) should be part of the TableContainer.

**Comment by titkov49** [comment]
Solved in this PR: https://github.com/TeskaLabs/asab-webui/pull/121
