### ISSUE TITLE
Inconsistent DateTime format in the DataTable

### ISSUE THREAD

**Issue by ateska** [TeskaLabs/asab-webui#113]
```
{
			name: 'DateTime',
			key: '_c',
			datetime: { format: 'lll' }
}
```

Here I need to specify the format - I need to have a way how to just say "this is datetime" and it will use default formatting from DateTime.

**Comment by titkov49** [comment]
@ateska Oh, there is a way to use default formatting for DateTime in DataTable. To do so, developer just need to pass true into datetime. It looks like this:
`{
			name: 'DateTime',
			key: '_c',
			datetime: true
}`

**Comment by ateska** [comment]
Ok, thanks.
I had a same idea, didn't find docs ;-(
